[package]
name = "onryou"
version = "0.0.1"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
hyper = { version = "1.5.0", features = ["full"] }
log = "0.4.22"
tokio = { version = "1.40.0", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
